site_name: USGS Astrogeology Software Docs

theme:
    name: material
    custom_dir: custom_theme/
    
    font:
      text: Inter
      code: Roboto Mono
    
    features:
        - navigation.tabs
        - navigation.expand
        - navigation.path
        - navigation.indexes
        - search.suggest
        - search.suggest

    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          accent: light blue
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: light blue
          toggle:
            icon: material/toggle-switch
            name: Switch to dark mode


nav:
  - Home: index.md
  - Getting Started: 
    - Home: getting-started/index.md
    - CSM Stack:
      - Generating an ISD, creating a CSM model, and converting coordinates: getting-started/CSM Stack/ImageToGroundTutorial.ipynb
  - How-To Guides: 
    - Home: how-to-guides/index.md
    - Software Management: 
      - ISIS Public Release Process: how-to-guides/Software Management/Public Release Process.md
      - Software Support: how-to-guides/Software Management/Software Support.md
    - ISIS Developer Guides:
      - How To Write ISIS Tests with CTest and GTest: "how-to-guides/ISIS Developer Guides/Writing ISIS Tests with CTest and GTest.md"
      - App Testing CookBook: "how-to-guides/ISIS Developer Guides/App Testing Cookbook.md"
      - Class Requirements For Using Doxygen Tags: "how-to-guides/ISIS Developer Guides/Class Requirements For Using Doxygen Tags.md"
  - Concepts: concepts/index.md
  - Manuals: manuals/index.md

extra_css:
  - css/neoteroi-mkdocs.css
  - css/extras.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/common.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/custom.css


extra_javascript: 
  -  https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/js/uswds-init.min.js

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true

markdown_extensions:
  - neoteroi.cards
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      title: On this page
      permalink: true
