site_name: USGS Astrogeology Software Docs

theme:
    name: material
    custom_dir: custom_theme/

    palette:
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          accent: light blue
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: light blue
          toggle:
            icon: material/toggle-switch
            name: Switch to dark mode


nav:
  - Links To Software Docs: index.md

extra_css:
  - css/neoteroi-mkdocs.css
  - css/extras.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/common.css
  - https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/css/custom.css


extra_javascript: 
  -  https://asc-public-docs.s3.us-west-2.amazonaws.com/common/uswds/3.6.0/js/uswds-init.min.js

markdown_extensions:
  - neoteroi.cards

